# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'questionbank.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Question_bank(object):
    def setupUi(self, Question_bank):
        Question_bank.setObjectName("Question_bank")
        Question_bank.resize(501, 419)
        Question_bank.setMinimumSize(QtCore.QSize(501, 419))
        Question_bank.setMaximumSize(QtCore.QSize(501, 419))
        self.centralwidget = QtWidgets.QWidget(Question_bank)
        self.centralwidget.setObjectName("centralwidget")
        self.question_group_box = QtWidgets.QGroupBox(self.centralwidget)
        self.question_group_box.setGeometry(QtCore.QRect(10, 20, 461, 331))
        self.question_group_box.setObjectName("question_group_box")
        self.question_list = QtWidgets.QListWidget(self.question_group_box)
        self.question_list.setGeometry(QtCore.QRect(10, 20, 231, 291))
        self.question_list.setObjectName("question_list")
        item = QtWidgets.QListWidgetItem()
        self.question_list.addItem(item)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.question_group_box)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(270, 210, 161, 98))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.add_question_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.add_question_button.setObjectName("add_question_button")
        self.verticalLayout_2.addWidget(self.add_question_button)
        self.modify_question_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.modify_question_button.setObjectName("modify_question_button")
        self.verticalLayout_2.addWidget(self.modify_question_button)
        self.delete_question_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.delete_question_button.setObjectName("delete_question_button")
        self.verticalLayout_2.addWidget(self.delete_question_button)
        self.question_lcd_number = QtWidgets.QLCDNumber(self.question_group_box)
        self.question_lcd_number.setGeometry(QtCore.QRect(270, 70, 161, 121))
        self.question_lcd_number.setObjectName("question_lcd_number")
        self.number_questions_label = QtWidgets.QLabel(self.question_group_box)
        self.number_questions_label.setGeometry(QtCore.QRect(280, 40, 131, 16))
        self.number_questions_label.setObjectName("number_questions_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 370, 461, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_question_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.save_question_button.setObjectName("save_question_button")
        self.horizontalLayout.addWidget(self.save_question_button)
        self.cancel_question_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancel_question_button.setObjectName("cancel_question_button")
        self.horizontalLayout.addWidget(self.cancel_question_button)
        Question_bank.setCentralWidget(self.centralwidget)


        self.retranslateUi(Question_bank)
        QtCore.QMetaObject.connectSlotsByName(Question_bank)

    def retranslateUi(self, Question_bank):
        _translate = QtCore.QCoreApplication.translate
        Question_bank.setWindowTitle(_translate("Question_bank", "Question Bank"))
        self.question_group_box.setTitle(_translate("Question_bank", "Question Bank"))
        __sortingEnabled = self.question_list.isSortingEnabled()
        self.question_list.setSortingEnabled(False)
        item = self.question_list.item(0)
        item.setText(_translate("Question_bank", "question1"))
        self.question_list.setSortingEnabled(__sortingEnabled)
        self.add_question_button.setText(_translate("Question_bank", "Add"))
        self.modify_question_button.setText(_translate("Question_bank", "Modify"))
        self.delete_question_button.setText(_translate("Question_bank", "Delete"))
        self.number_questions_label.setText(_translate("Question_bank", "Number of questions:"))
        self.save_question_button.setText(_translate("Question_bank", "Save"))
        self.cancel_question_button.setText(_translate("Question_bank", "Cancel"))
